### ISSUE TITLE
Cross hair not visible in HMD

### ISSUE THREAD

**Issue by DerpedCrusader** [LivingFray/HaloCEVR#10] opened 2024-11-28 01:12 UTC
Cross hair isn't visible in the HMD during gameplay, but is visible when the game is paused, also visible in the VR view

Footage of me realizing the cross hair was visible through the VR view:
https://github.com/user-attachments/assets/ec7413bf-a345-486e-b4f8-78af7449eab9

Set up: oculus Quest 2 connected to PC wirelessly via "Steam link" app

Used the chimera mod, and I made sure to change the font setting

**Comment by avolpe95** [comment] 2024-11-28 02:34
Have the same issue with steam link app. It's fine with air link and virtual desktop but vd has some warping issues. Quest link seems to be the way to go for this game

**Comment by albrechtjess** [comment] 2024-11-28 03:45
Odd to hear it's fine with air link and VD. I'm also using steam link and have the crosshair issue.

**Comment by albrechtjess** [comment] 2024-11-28 04:15
Huh oddly the reticle shows up for the sniper using steam link?

**Comment by RocketMan2007** [comment] 2024-11-28 05:54
Meta Quest 3 using steam link and the only reticle that shows up is the sniper rifle.

**Comment by DerpedCrusader** [comment] 2024-11-28 14:19
> Have the same issue with steam link app. It's fine with air link and virtual desktop but vd has some warping issues. Quest link seems to be the way to go for this game

Guess I'll give it a shot over the wired link

**Comment by LivingFray** [comment] 2024-11-29 01:42
The crosshair and UI are both steam overlays (but sniper scope is its own thing drawn directly in world), its possible steam link is only rendering the first (or last?) overlay its given. 
Since I don't own any standalone headsets I can't exactly test this theory or reproduce the issue locally however...

**Comment by RocketMan2007** [comment] 2024-11-29 15:03
> The crosshair and UI are both steamvr overlays (but sniper scope is its own thing drawn directly in world), its possible steam link is only rendering the first (or last?) overlay its given. Since I don't own any standalone headsets I can't exactly test this theory or reproduce the issue locally however...

Ok, thank you for the info. I will try to dig in a bit and see if I can locate the disconnect. Over all it's really not terrible not having a reticle. FANTASTIC job on this mod by the way. Can't express enough how much fun it is.

**Comment by creamcast** [comment] 2024-11-29 20:14
I wanted to chime in and mention that I personally prefer playing without crosshairs, as it feels more immersive in VR. For now I'm using this bug to play without them since I couldn't find a way to turn it off in the settings or config files. It would be nice to have the option to toggle the crosshair on and off in future versions.

Thanks for all the work on the mod, it’s awesome!

**Comment by Charliyo** [comment] 2024-12-01 12:00
Some additional testing I tried on this - no issues at all when cabled. Steam and ALVR both hide the crosshair, I don't have virtual desktop to run testing through that but since ALVR also uses SteamVR as a base, I support the theory about overlays.

Wish I had a way to work this wirelessly though, I don't normally play in the same room as my PC

**Comment by LivingFray** [comment] 2024-12-01 15:06
I've rewritten the crosshair rendering logic to avoid using overlays and instead draw it directly into the world. This issue should be resolved in 1.1.0 (and if anyone was [intentionally using this bug](https://xkcd.com/1172/) because they didn't want a crosshair: I've added an option to turn off the crosshair too)

**Closed by LivingFray** 2024-12-01 15:06 UTC
